const user_types = {
  USER_LOGIN_START: "USER_LOGIN_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_DATA: "USER_DATA",
  INITIAL_FORM_VAL: "INITIAL_FORM_VAL",
  ADD_POSTED_JOBS: "ADD_POSTED_JOBS",
  UPDATE_EDUCATION: "UPDATE_EDUCATION",
};
export default user_types;
