const user_types = {
  USER_LOGIN_START: "USER_LOGIN_START",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
  USER_DATA: "USER_DATA",
  INITIAL_FORM_VAL: "INITIAL_FORM_VAL",
  SET_USER_TOKEN: "SET_USER_TOKEN",
};
export default user_types;
