const job_types = {
  JOBS_FETCHING_START: "JOBS_FETCHING_START",
  JOBS_FETCHING_SUCCESS: "JOBS_FETCHING_SUCCESS",
  JOBS_FETCHING_FAILED: "JOBS_FETCHING_FAILED",
  JOB_FILTER_SUCCESS: "JOB_FILTER_SUCCESS",
  JOB_FILTER_RESET: "JOB_FILTER_RESET",
  JOB_DRAWER_OPEN: "JOB_DRAWER_OPEN",
};
export default job_types;
